updated github and readthedocs documentation
uploadcare/pyuploadcare pull request #202
Opened 2022-04-14 11:00 UTC by art-vasilyev

## Description

Updated github README.rst and readthedocs documentation.

2022-04-14 11:43 UTC, rsedykh requested changes
Maybe we should remove docs from readme and link it to RTD?

2022-04-14 11:43 UTC, rsedykh commented on README.rst
> +``UPLOADCARE['widget_build']`` instead.
А нам это надо в ридми?

2022-04-14 11:43 UTC, rsedykh commented on docs/index.rst
> +Simple as that, Uploadcare ``ImageField`` can be added to an
А почему в итоге пример с ImageField, а не с FieldField?

2022-04-14 11:43 UTC, rsedykh commented on docs/index.rst
>     deprecated
deprecated не хотим полностью удалить?

2022-04-14 11:52 UTC, art-vasilyev commented on README.rst
> +``UPLOADCARE['widget_build']`` instead.
Согласен, в readme я бы оставил только вводную часть, а всё остальное по ссылке на readthedocs. Но для этого надо сначала сборку доки на readthedocs починить

2022-04-14 11:53 UTC, rsedykh commented on README.rst
> +``UPLOADCARE['widget_build']`` instead.
Ну давай мы PR подготовим сразу хороший. :-)

2022-04-14 12:14 UTC, art-vasilyev commented on docs/index.rst
> +Simple as that, Uploadcare ``ImageField`` can be added to an
логичнее в примере ImageField показать, так как у него больше функционала

2022-04-14 12:14 UTC, art-vasilyev commented on docs/index.rst
>     deprecated
done

2022-04-14 12:23 UTC, art-vasilyev commented on README.rst
> +``UPLOADCARE['widget_build']`` instead.
оставил самый минимум в ридми

2022-04-18 15:54 UTC, rsedykh commented
Please check my commits.

2022-04-19 12:04 UTC, art-vasilyev commented
> Please check my commits.

Looks good

2022-07-27 13:57 UTC, merged