Add deprecation warnings for GroupsAPI.storage and FileGroup.datetime_stored
uploadcare/pyuploadcare pull request #271
Opened 2023-11-10 20:17 UTC by evgkirov

## Description

Related issue: #261 

Added just a couple `DeprecationWarning`s

## Checklist

- [ ] Tests (if applicable)
- [ ] Documentation (if applicable)
- [x] Changelog stub (or use [conventional commit messages](https://www.conventionalcommits.org/))

2023-11-13 12:08 UTC, dmitry-mukhin requested changes

2023-11-13 12:08 UTC, dmitry-mukhin commented on HISTORY.md
> +### Changed
```suggestion
### Deprecated
```

2023-11-16 19:45 UTC, evgkirov commented
See comment https://github.com/uploadcare/pyuploadcare/issues/261#issuecomment-1815196764

2023-12-01 13:18 UTC, dmitry-mukhin approved these changes

2023-12-01 18:52 UTC, merged