feat(file-uploader): Updated @uploadcare/blocks to @uploadcare/file-u…
uploadcare/pyuploadcare pull request #296
Opened 2024-08-18 14:49 UTC by egordidenko

…ploader

## Description

## Checklist

- [ ] Tests (if applicable)
- [ ] Documentation (if applicable)
- [ ] Changelog stub (or use [conventional commit messages](https://www.conventionalcommits.org/))

2024-08-18 22:00 UTC, rsedykh commented on pyuploadcare/dj/conf.py
> +        "version": "1.4.0",
Maybe 1.* since no breaking changes?

2024-09-18 20:17 UTC, dmitry-mukhin requested changes
add changelog entry and we need new major pyuploadcare version.

2024-09-19 13:50 UTC, evgkirov commented
Integration tests are failing.

2024-09-24 12:32 UTC, rsedykh commented
Merge on behalf of @egordidenko

2024-09-24 12:32 UTC, merged